"""
TokenPak Recipe SDK — Custom recipe development tooling.

Provides scaffolding, validation, testing, and benchmarking for
custom compression recipes (YAML-based declarative format).

Usage (CLI layer in cli.py):
    tokenpak recipe create <name>
    tokenpak recipe test   <file>
    tokenpak recipe validate <file>
    tokenpak recipe benchmark <file>

Programmatic usage::

    from tokenpak.compression.recipe_sdk import RecipeSDK
    sdk = RecipeSDK()
    sdk.validate("my_recipe.yaml")
    result = sdk.test("my_recipe.yaml", input_text="...")
    bench  = sdk.benchmark("my_recipe.yaml", samples=[...])
"""

from __future__ import annotations

import json
import re
import time
from pathlib import Path
from typing import Any

import yaml

# ── Schema ────────────────────────────────────────────────────────────────────

RECIPE_SCHEMA: dict[str, Any] = {
    "required_top_level": ["name", "category", "description", "pattern", "action"],
    "pattern_keys": {
        "required": ["match"],
        "match_modes": ["any", "extension", "filename", "content", "path_pattern"],
        "match_mode_keys": {
            "extension": ["extensions"],
            "filename": ["filenames"],
            "content": ["keywords"],
            "path_pattern": ["path_patterns"],
        },
    },
    "action_keys": {
        "required": ["operations"],
        "optional": ["compression_hint"],
        "compression_hint_range": (0.0, 1.0),
    },
    "known_operation_types": [
        "regex_replace",
        "strip_comments",
        "deduplicate_lines",
        "truncate_lines",
        "remove_empty_lines",
        "python_docstring_compress",
        "collapse_whitespace",
        "remove_filler_phrases",
        "json_compact",
        "keyword_filter",
    ],
    "known_categories": [
        "python",
        "javascript",
        "typescript",
        "markdown",
        "yaml",
        "json",
        "sql",
        "html",
        "css",
        "general",
        "legal",
        "medical",
        "config",
        "logs",
        "git",
    ],
}

# ── SCAFFOLD TEMPLATE ─────────────────────────────────────────────────────────

_SCAFFOLD_TEMPLATE = """\
# TokenPak Custom Recipe: {name}
# Generated by: tokenpak recipe create
# Docs: https://docs.tokenpak.ai/recipes
#
# Edit this file to define your compression behaviour, then:
#   tokenpak recipe validate {filename}
#   tokenpak recipe test     {filename}
#   tokenpak recipe benchmark {filename}

name: {name}
category: {category}   # e.g. python, markdown, legal, medical, general
description: "{description}"

pattern:
  match: {match_mode}   # any | extension | filename | content | path_pattern
  # For match: extension
  extensions:
    - .{ext}
  # For match: content
  # keywords:
  #   - "def "
  #   - "class "

action:
  compression_hint: 0.2   # Expected fraction removed (0.0–1.0)
  operations:
    - type: strip_comments
    - type: collapse_whitespace
    # - type: regex_replace
    #   pattern: "^\\\\s*#.*$"
    #   replacement: ""
    #   flags: ["MULTILINE"]
    # - type: deduplicate_lines
    # - type: truncate_lines
    #   max_length: 120
    # - type: remove_empty_lines
    #   max_consecutive: 2
"""

# ── Domain-specific example recipes ──────────────────────────────────────────

DOMAIN_EXAMPLE_RECIPES: dict[str, dict[str, Any]] = {
    "legal": {
        "name": "legal-boilerplate-removal",
        "category": "legal",
        "description": "Remove standard legal boilerplate and recitals to focus on operative clauses.",
        "pattern": {
            "match": "content",
            "keywords": ["WHEREAS", "NOW, THEREFORE", "IN WITNESS WHEREOF", "RECITALS"],
        },
        "action": {
            "compression_hint": 0.35,
            "operations": [
                {
                    "type": "regex_replace",
                    "pattern": r"WHEREAS[^;]+;",
                    "replacement": "[WHEREAS RECITAL OMITTED]",
                    "flags": ["DOTALL"],
                },
                {
                    "type": "regex_replace",
                    "pattern": r"IN WITNESS WHEREOF[^.]+\.",
                    "replacement": "[SIGNATURE BLOCK OMITTED]",
                    "flags": ["DOTALL"],
                },
                {"type": "collapse_whitespace"},
                {"type": "remove_empty_lines", "max_consecutive": 1},
            ],
        },
    },
    "medical": {
        "name": "medical-boilerplate-removal",
        "category": "medical",
        "description": "Strip administrative headers and standard disclaimers from clinical notes.",
        "pattern": {
            "match": "content",
            "keywords": ["PATIENT:", "DOB:", "MRN:", "CONFIDENTIALITY NOTICE"],
        },
        "action": {
            "compression_hint": 0.25,
            "operations": [
                {
                    "type": "regex_replace",
                    "pattern": r"CONFIDENTIALITY NOTICE[^\n]+\n",
                    "replacement": "",
                    "flags": ["MULTILINE"],
                },
                {
                    "type": "regex_replace",
                    "pattern": r"(Patient Name|DOB|MRN|Date of Birth): [^\n]+\n",
                    "replacement": "",
                    "flags": ["MULTILINE", "IGNORECASE"],
                },
                {"type": "collapse_whitespace"},
            ],
        },
    },
}


# ── RecipeSDK ─────────────────────────────────────────────────────────────────


class RecipeValidationError(ValueError):
    """Raised when a recipe file fails schema validation."""


class RecipeSDK:
    """Tooling for developing, testing, and benchmarking custom recipes."""

    # ── Create ────────────────────────────────────────────────────────────────

    def create(
        self,
        name: str,
        *,
        output_dir: str | Path = ".",
        category: str = "general",
        description: str = "",
        match_mode: str = "extension",
        ext: str = "txt",
        domain_example: str | None = None,
    ) -> Path:
        """Scaffold a new recipe YAML file.

        Args:
            name: Recipe name (used as filename if no output_dir conflict).
            output_dir: Directory to write the file into.
            category: Recipe category hint.
            description: Short description for the recipe.
            match_mode: Default pattern match mode.
            ext: File extension hint (for extension match mode).
            domain_example: If "legal" or "medical", emit a domain-specific template.

        Returns:
            Path to the created file.
        """
        # Sanitise name: lowercase, hyphens
        safe_name = re.sub(r"[^a-z0-9-]", "-", name.lower()).strip("-")
        filename = f"{safe_name}.yaml"
        out = Path(output_dir) / filename

        if domain_example and domain_example in DOMAIN_EXAMPLE_RECIPES:
            content = yaml.dump(
                DOMAIN_EXAMPLE_RECIPES[domain_example],
                default_flow_style=False,
                sort_keys=False,
                allow_unicode=True,
            )
            header = (
                f"# TokenPak Custom Recipe: {safe_name}\n"
                f"# Domain example: {domain_example}\n"
                f"# Generated by: tokenpak recipe create\n\n"
            )
            content = header + content
        else:
            content = _SCAFFOLD_TEMPLATE.format(
                name=safe_name,
                filename=filename,
                category=category,
                description=description or f"Custom recipe for {safe_name}",
                match_mode=match_mode,
                ext=ext,
            )

        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(content, encoding="utf-8")
        return out

    # ── Validate ──────────────────────────────────────────────────────────────

    def validate(self, recipe_file: str | Path) -> list[str]:
        """Validate a recipe file against the schema.

        Returns:
            List of warning strings (empty == fully valid).

        Raises:
            RecipeValidationError: On hard schema violations.
        """
        path = Path(recipe_file)
        if not path.exists():
            raise RecipeValidationError(f"File not found: {path}")

        raw = yaml.safe_load(path.read_text(encoding="utf-8"))
        if not isinstance(raw, dict):
            raise RecipeValidationError("Recipe must be a YAML mapping at the top level.")

        errors: list[str] = []
        warnings: list[str] = []

        # Top-level required fields
        for field in RECIPE_SCHEMA["required_top_level"]:
            if field not in raw:
                errors.append(f"Missing required field: '{field}'")

        if errors:
            raise RecipeValidationError("; ".join(errors))

        # name / category / description
        if not str(raw.get("name", "")).strip():
            errors.append("Field 'name' must be a non-empty string.")
        if not str(raw.get("category", "")).strip():
            errors.append("Field 'category' must be a non-empty string.")
        cat = str(raw.get("category", "")).strip()
        if cat and cat not in RECIPE_SCHEMA["known_categories"]:
            warnings.append(
                f"Unknown category '{cat}'. Known: {', '.join(RECIPE_SCHEMA['known_categories'])}. "
                "This is allowed but may reduce discoverability."
            )
        if not str(raw.get("description", "")).strip():
            warnings.append(
                "Field 'description' is empty — add a short description for discoverability."
            )

        # pattern
        pattern = raw.get("pattern", {})
        if not isinstance(pattern, dict):
            errors.append("Field 'pattern' must be a mapping.")
        else:
            if "match" not in pattern:
                errors.append("pattern.match is required.")
            else:
                mode = pattern["match"]
                valid_modes = RECIPE_SCHEMA["pattern_keys"]["match_modes"]
                if mode not in valid_modes:
                    errors.append(f"pattern.match '{mode}' invalid. Valid: {valid_modes}")
                else:
                    mode_keys = RECIPE_SCHEMA["pattern_keys"]["match_mode_keys"]
                    if mode in mode_keys:
                        required_key = mode_keys[mode][0]
                        if required_key not in pattern:
                            errors.append(
                                f"pattern.match='{mode}' requires pattern.{required_key} list."
                            )

        # action
        action = raw.get("action", {})
        if not isinstance(action, dict):
            errors.append("Field 'action' must be a mapping.")
        else:
            if "operations" not in action:
                errors.append("action.operations is required.")
            elif not isinstance(action["operations"], list):
                errors.append("action.operations must be a list.")
            elif len(action["operations"]) == 0:
                warnings.append("action.operations is empty — recipe will have no effect.")
            else:
                known_ops = RECIPE_SCHEMA["known_operation_types"]
                for i, op in enumerate(action["operations"]):
                    if not isinstance(op, dict):
                        errors.append(f"action.operations[{i}] must be a mapping.")
                        continue
                    if "type" not in op:
                        errors.append(f"action.operations[{i}] missing 'type'.")
                        continue
                    op_type = op["type"]
                    if op_type not in known_ops:
                        warnings.append(
                            f"action.operations[{i}].type '{op_type}' is not a built-in operation. "
                            "This is allowed for custom engines but verify spelling."
                        )

            hint = action.get("compression_hint")
            if hint is not None:
                lo, hi = RECIPE_SCHEMA["action_keys"]["compression_hint_range"]
                try:
                    h = float(hint)
                    if not (lo <= h <= hi):
                        errors.append(f"action.compression_hint {h} out of range [{lo}, {hi}].")
                except (TypeError, ValueError):
                    errors.append("action.compression_hint must be a float.")

        if errors:
            raise RecipeValidationError("; ".join(errors))

        return warnings

    # ── Test ─────────────────────────────────────────────────────────────────

    def test(
        self,
        recipe_file: str | Path,
        *,
        input_text: str | None = None,
        input_file: str | Path | None = None,
        filename_hint: str = "",
    ) -> dict[str, Any]:
        """Test a recipe against sample input.

        Validates the recipe, checks pattern matching, and simulates
        operation application where possible.

        Args:
            recipe_file: Path to recipe YAML.
            input_text: Raw text to test against.
            input_file: Path to a file to read as input.
            filename_hint: Filename to check pattern matching against.

        Returns:
            Dict with keys: valid, warnings, pattern_match, ops_applied,
            input_size, output_size, compression_ratio, output_preview.
        """
        path = Path(recipe_file)
        warnings = self.validate(path)
        raw = yaml.safe_load(path.read_text(encoding="utf-8"))

        # Resolve input
        if input_file is not None:
            text = Path(input_file).read_text(encoding="utf-8", errors="replace")
            if not filename_hint:
                filename_hint = str(input_file)
        elif input_text is not None:
            text = input_text
        else:
            text = _default_sample_for_category(raw.get("category", "general"))

        # Pattern matching check
        from tokenpak.compression.recipes import CompressionRecipe

        recipe_obj = CompressionRecipe.from_dict(raw, source=str(path))
        pattern_match = recipe_obj.matches(filename=filename_hint, content_sample=text[:2000])

        # Apply operations (best-effort simulation)
        result_text, ops_applied = _apply_operations(
            text, raw.get("action", {}).get("operations", [])
        )

        input_size = len(text)
        output_size = len(result_text)
        ratio = (input_size - output_size) / max(input_size, 1)

        return {
            "valid": True,
            "warnings": warnings,
            "pattern_match": pattern_match,
            "filename_hint": filename_hint or "(none)",
            "ops_applied": ops_applied,
            "input_chars": input_size,
            "output_chars": output_size,
            "compression_ratio": round(ratio, 4),
            "compression_hint": raw.get("action", {}).get("compression_hint", None),
            "output_preview": result_text[:500] + ("…" if len(result_text) > 500 else ""),
        }

    # ── Benchmark ─────────────────────────────────────────────────────────────

    def benchmark(
        self,
        recipe_file: str | Path,
        *,
        samples: list[str] | None = None,
        runs: int = 5,
    ) -> dict[str, Any]:
        """Benchmark a recipe's compression ratio and speed.

        Args:
            recipe_file: Path to recipe YAML.
            samples: List of text strings to benchmark against.
                     Defaults to 3 category-appropriate samples.
            runs: Number of repetitions per sample for timing.

        Returns:
            Dict with aggregate stats: mean_compression, min_compression,
            max_compression, mean_ms, total_chars_processed.
        """
        path = Path(recipe_file)
        self.validate(path)
        raw = yaml.safe_load(path.read_text(encoding="utf-8"))
        operations = raw.get("action", {}).get("operations", [])
        category = raw.get("category", "general")

        if not samples:
            samples = [_default_sample_for_category(category) for _ in range(3)]

        ratios: list[float] = []
        times_ms: list[float] = []
        total_chars = 0

        for sample in samples:
            total_chars += len(sample)
            for _ in range(runs):
                t0 = time.perf_counter()
                result, _ = _apply_operations(sample, operations)
                elapsed_ms = (time.perf_counter() - t0) * 1000
                times_ms.append(elapsed_ms)

            result, _ = _apply_operations(sample, operations)
            ratio = (len(sample) - len(result)) / max(len(sample), 1)
            ratios.append(ratio)

        return {
            "recipe": raw.get("name", path.stem),
            "category": category,
            "samples_tested": len(samples),
            "runs_per_sample": runs,
            "total_chars_processed": total_chars,
            "compression": {
                "mean": round(sum(ratios) / len(ratios), 4),
                "min": round(min(ratios), 4),
                "max": round(max(ratios), 4),
            },
            "timing_ms": {
                "mean": round(sum(times_ms) / len(times_ms), 3),
                "min": round(min(times_ms), 3),
                "max": round(max(times_ms), 3),
            },
            "hint_vs_actual": {
                "hint": raw.get("action", {}).get("compression_hint"),
                "actual_mean": round(sum(ratios) / len(ratios), 4),
            },
        }


# ── Operation dispatcher ──────────────────────────────────────────────────────


def _apply_operations(text: str, operations: list[dict[str, Any]]) -> tuple[str, list[str]]:
    """Apply a list of recipe operations to text. Returns (result, applied_op_names)."""
    applied: list[str] = []
    result = text

    for op in operations:
        op_type = op.get("type", "")

        if op_type == "regex_replace":
            pattern = op.get("pattern", "")
            replacement = op.get("replacement", "")
            flag_names = op.get("flags", [])
            flags = 0
            for fn in flag_names:
                flags |= getattr(re, fn, 0)
            try:
                result = re.sub(pattern, replacement, result, flags=flags)
                applied.append(op_type)
            except re.error:
                pass  # bad pattern — skip

        elif op_type == "strip_comments":
            # Strip # single-line comments
            result = re.sub(r"(?m)^\s*#.*\n?", "", result)
            applied.append(op_type)

        elif op_type == "deduplicate_lines":
            seen: set[str] = set()
            lines = []
            for line in result.splitlines():
                stripped = line.strip()
                if stripped not in seen:
                    seen.add(stripped)
                    lines.append(line)
            result = "\n".join(lines)
            applied.append(op_type)

        elif op_type == "truncate_lines":
            max_len = int(op.get("max_length", 120))
            result = "\n".join(line[:max_len] for line in result.splitlines())
            applied.append(op_type)

        elif op_type == "remove_empty_lines":
            max_consecutive = int(op.get("max_consecutive", 1))
            result = re.sub(
                r"\n{" + str(max_consecutive + 1) + r",}", "\n" * max_consecutive, result
            )
            applied.append(op_type)

        elif op_type == "collapse_whitespace":
            result = re.sub(r"[ \t]+", " ", result)
            result = re.sub(r"\n{3,}", "\n\n", result)
            applied.append(op_type)

        elif op_type == "python_docstring_compress":
            mode = op.get("mode", "keep_summary")
            if mode == "remove":
                result = re.sub(r'"""[\s\S]*?"""', '""""""', result)
                result = re.sub(r"'''[\s\S]*?'''", "''''''", result)
            elif mode == "keep_summary":

                def _compress_docstring(m: re.Match[str]) -> str:
                    inner = m.group(0)[3:-3].strip()
                    first_line = inner.split("\n")[0].strip()
                    quote = m.group(0)[:3]
                    return f"{quote}{first_line}{quote}"

                result = re.sub(r'"""[\s\S]*?"""', _compress_docstring, result)
            applied.append(op_type)

        elif op_type == "remove_filler_phrases":
            fillers = [
                r"\bIn conclusion\b,?\s*",
                r"\bIt is worth noting that\b\s*",
                r"\bIt should be noted that\b\s*",
                r"\bAs mentioned (above|before|earlier)\b,?\s*",
                r"\bNeedless to say\b,?\s*",
                r"\bObviously\b,?\s*",
                r"\bClearly\b,?\s*",
            ]
            for filler in fillers:
                result = re.sub(filler, "", result, flags=re.IGNORECASE)
            applied.append(op_type)

        elif op_type == "json_compact":
            try:
                parsed = json.loads(result)
                result = json.dumps(parsed, separators=(",", ":"))
                applied.append(op_type)
            except json.JSONDecodeError:
                pass

        elif op_type == "keyword_filter":
            keep_keywords = op.get("keep_keywords", [])
            if keep_keywords:
                lines = [
                    line for line in result.splitlines() if any(kw in line for kw in keep_keywords)
                ]
                result = "\n".join(lines)
                applied.append(op_type)

    return result, applied


# ── Sample generator ──────────────────────────────────────────────────────────


def _default_sample_for_category(category: str) -> str:
    """Return a representative text sample for a given recipe category."""
    samples = {
        "python": '''\
def calculate_total(items: list[dict]) -> float:
    """
    Calculate the total price of all items in the shopping cart.

    This function iterates over each item in the provided list and
    sums up the price * quantity for each item.

    Args:
        items: A list of item dictionaries with 'price' and 'qty' keys.

    Returns:
        The total price as a float.
    """
    # Initialize total
    total = 0.0
    # Loop over items
    for item in items:
        total += item["price"] * item["qty"]
    return total
''',
        "legal": """\
AGREEMENT

WHEREAS, Company A ("Client") desires to engage the services of Company B;
WHEREAS, Company B desires to provide such services to Client;
NOW, THEREFORE, in consideration of the mutual covenants herein, the parties agree:

1. SERVICES. Company B shall provide consulting services.
2. PAYMENT. Client shall pay $5,000 per month.

IN WITNESS WHEREOF, the parties have executed this Agreement as of the date first written above.
""",
        "medical": """\
Patient Name: John Doe
DOB: 01/15/1970
MRN: 12345678
Date: 2026-03-05

CONFIDENTIALITY NOTICE: This document contains protected health information.

CHIEF COMPLAINT: Patient presents with chest pain.
HISTORY: 3-day history of intermittent chest discomfort.
ASSESSMENT: Rule out cardiac etiology.
PLAN: Order EKG, troponin levels. Refer to cardiology.
""",
        "markdown": """\
# Introduction

In conclusion, this document describes the setup process.

It should be noted that the configuration is optional.

## Installation

- Step 1: Download the package
- Step 2: Download the package
- Step 3: Run the installer
- Step 3: Run the installer

## Conclusion

Clearly, the process is straightforward.
""",
        "general": """\
This document contains information about the system.
This document contains information about the system.

   Extra   whitespace   here   is   unnecessary.

In conclusion, the system works as described.
It is worth noting that configuration is required.
It should be noted that defaults are provided.
""",
    }
    return samples.get(category, samples["general"])
