#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# ──────────────────────────────────────────────────────────────
# Codex UserPromptSubmit hook — pure bash, ~30ms target.
#
# Reads JSON from stdin with: session_id, transcript_path, cwd,
# hook_event_name, model, prompt.
#
# Outputs:
#   - Cost estimate to stderr (visible in Codex TUI)
#   - Budget block via exit code 2 if over limit
# ──────────────────────────────────────────────────────────────

INPUT=$(cat)

[ "${TOKENPAK_COMPANION_ENABLED:-1}" = "0" ] && exit 0

if command -v jq >/dev/null 2>&1; then
    TRANSCRIPT=$(echo "$INPUT" | jq -r '.transcript_path // empty' 2>/dev/null)
    SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // empty' 2>/dev/null)
    MODEL=$(echo "$INPUT" | jq -r '.model // empty' 2>/dev/null)
else
    TRANSCRIPT=$(echo "$INPUT" | sed -n 's/.*"transcript_path"\s*:\s*"\([^"]*\)".*/\1/p')
    SESSION_ID=$(echo "$INPUT" | sed -n 's/.*"session_id"\s*:\s*"\([^"]*\)".*/\1/p')
    MODEL=$(echo "$INPUT" | sed -n 's/.*"model"\s*:\s*"\([^"]*\)".*/\1/p')
fi

TOKENS=0
if [ -n "$TRANSCRIPT" ] && [ -f "$TRANSCRIPT" ]; then
    FILE_SIZE=$(stat -c%s "$TRANSCRIPT" 2>/dev/null || stat -f%z "$TRANSCRIPT" 2>/dev/null || echo 0)
    TOKENS=$((FILE_SIZE / 4))
fi

[ "$TOKENS" -eq 0 ] && exit 0

TOKENS_FMT=$(printf '%d' "$TOKENS" | rev | sed 's/.\{3\}/&,/g' | rev | sed 's/^,//')

# Rate lookup: TSV snapshot generated by rates_snapshot.py — avoids
# hardcoded model enumerations (see feedback_always_dynamic.md rule).
# Fallback rate 3 matches registry's _UNKNOWN_DEFAULT for unknown models.
RATES_FILE="${TOKENPAK_COMPANION_RATES_FILE:-$HOME/.tokenpak/companion/run/model_rates.tsv}"
RATE=3
if [ -n "$MODEL" ] && [ -f "$RATES_FILE" ]; then
    # Exact match first, then prefix match (e.g. "gpt-4o-2026-01-01" → "gpt-4o")
    RATE=$(awk -F'\t' -v m="$MODEL" '
        $1 == m { print $2; exit }
    ' "$RATES_FILE" 2>/dev/null)
    if [ -z "$RATE" ]; then
        RATE=$(awk -F'\t' -v m="$MODEL" '
            BEGIN { best_len = 0; best = "" }
            index(m, $1) == 1 && length($1) > best_len { best_len = length($1); best = $2 }
            END { if (best != "") print best }
        ' "$RATES_FILE" 2>/dev/null)
    fi
    [ -z "$RATE" ] && RATE=3
fi

COST_MICRO=$((TOKENS * RATE / 1000))
COST_DOLLARS="$((COST_MICRO / 1000)).$(printf '%04d' $((COST_MICRO % 1000)))"

BUDGET="${TOKENPAK_COMPANION_BUDGET:-0}"
BUDGET_TAG=""

if [ "$BUDGET" != "0" ] && [ -n "$BUDGET" ]; then
    JOURNAL_DIR="${TOKENPAK_COMPANION_JOURNAL_DIR:-$HOME/.tokenpak/companion}"
    BUDGET_DB="$JOURNAL_DIR/budget.db"
    TODAY=$(date +%Y-%m-%d)
    DAILY_TOTAL="0.0"

    if [ -f "$BUDGET_DB" ] && command -v sqlite3 >/dev/null 2>&1; then
        DAILY_TOTAL=$(sqlite3 "$BUDGET_DB" \
            "SELECT COALESCE(SUM(estimated_cost), 0) FROM companion_costs WHERE date = '$TODAY';" 2>/dev/null || echo "0.0")
    fi

    BUDGET_MICRO=$(echo "$BUDGET * 1000000" | bc 2>/dev/null | cut -d. -f1 || echo 0)
    DAILY_MICRO=$(echo "$DAILY_TOTAL * 1000000" | bc 2>/dev/null | cut -d. -f1 || echo 0)
    EST_MICRO=$((TOKENS * RATE))

    if [ "$((DAILY_MICRO + EST_MICRO))" -gt "${BUDGET_MICRO:-0}" ] 2>/dev/null; then
        MSG="tokenpak: budget exceeded (\$$DAILY_TOTAL / \$$BUDGET daily)"
        echo "$MSG" >&2
        # Codex hookSpecificOutput JSON block (audit delta hooks #3).
        # Mirrors companion/hooks/pre_send.py:103-110 + .sh reference.
        REASON=$(printf '%s' "$MSG" | sed 's/\\/\\\\/g; s/"/\\"/g')
        printf '{"hookSpecificOutput":{"hookEventName":"UserPromptSubmit","decision":"block","reason":"%s"}}\n' "$REASON"
        exit 2
    fi

    if [ "${BUDGET_MICRO:-0}" -gt 0 ] 2>/dev/null; then
        PCT=$((DAILY_MICRO * 100 / BUDGET_MICRO))
        [ "$PCT" -gt 50 ] && BUDGET_TAG="  budget ${PCT}%"
    fi
fi

if [ "${TOKENPAK_COMPANION_SHOW_COST:-1}" != "0" ]; then
    MODEL_TAG=""
    [ -n "$MODEL" ] && MODEL_TAG=" ($MODEL)"
    printf 'tokenpak: ~%s tokens  est $%s%s%s\n' "$TOKENS_FMT" "$COST_DOLLARS" "$MODEL_TAG" "$BUDGET_TAG" >&2
fi

if [ -n "$SESSION_ID" ]; then
    JOURNAL_DIR="${TOKENPAK_COMPANION_JOURNAL_DIR:-$HOME/.tokenpak/companion}"
    JOURNAL_DB="$JOURNAL_DIR/journal.db"
    if [ -f "$JOURNAL_DB" ] && command -v sqlite3 >/dev/null 2>&1; then
        TIMESTAMP=$(date +%s)
        sqlite3 "$JOURNAL_DB" \
            "INSERT OR IGNORE INTO entries (session_id, timestamp, entry_type, content, metadata_json)
             VALUES ('$SESSION_ID', $TIMESTAMP, 'auto', 'prompt submitted (~${TOKENS_FMT} tokens, est \$$COST_DOLLARS, model: ${MODEL:-unknown})', '{}');" 2>/dev/null &
    fi
fi

exit 0
