#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# ──────────────────────────────────────────────────────────────
# Ultra-lean UserPromptSubmit hook — pure bash, ~30ms target.
#
# No python3 in the hot path. JSON fields extracted with grep.
# Budget check uses sqlite3 CLI (only if budget is set).
# ──────────────────────────────────────────────────────────────

# Read stdin
INPUT=$(cat)

# Quick exit if companion disabled
[ "${TOKENPAK_COMPANION_ENABLED:-1}" = "0" ] && exit 0

# Parse JSON fields — try jq first (fastest), fall back to sed (portable)
if command -v jq >/dev/null 2>&1; then
    _TP_FIELDS=()
    mapfile -t _TP_FIELDS < <(
        printf '%s' "$INPUT" | jq -r '(.transcript_path // ""), (.session_id // ""), (.model // "")' 2>/dev/null
    )
    TRANSCRIPT="${_TP_FIELDS[0]:-}"
    SESSION_ID="${_TP_FIELDS[1]:-}"
    MODEL="${_TP_FIELDS[2]:-}"
else
    # Portable sed extraction (no -P flag needed)
    TRANSCRIPT=$(echo "$INPUT" | sed -n 's/.*"transcript_path"\s*:\s*"\([^"]*\)".*/\1/p')
    SESSION_ID=$(echo "$INPUT" | sed -n 's/.*"session_id"\s*:\s*"\([^"]*\)".*/\1/p')
    MODEL=$(echo "$INPUT" | sed -n 's/.*"model"\s*:\s*"\([^"]*\)".*/\1/p')
fi

_tp_block_budget() {
    MSG="$1"
    echo "$MSG" >&2
    REASON=$(printf '%s' "$MSG" | sed 's/\\/\\\\/g; s/"/\\"/g')
    printf '{"hookSpecificOutput":{"hookEventName":"UserPromptSubmit","decision":"block","reason":"%s"}}\n' "$REASON"
    exit 2
}

_tp_to_micro() {
    awk -v v="$1" 'BEGIN {
        if (v !~ /^[0-9]+([.][0-9]+)?$/) exit 1
        printf "%.0f\n", v * 1000000
    }' 2>/dev/null
}

_tp_entry_hash() {
    if command -v sha256sum >/dev/null 2>&1; then
        printf '%s\037%s\037%s' "$1" "$2" "$3" | sha256sum 2>/dev/null | awk '{print $1}'
    elif command -v shasum >/dev/null 2>&1; then
        printf '%s\037%s\037%s' "$1" "$2" "$3" | shasum -a 256 2>/dev/null | awk '{print $1}'
    fi
}

_tp_ensure_dedupe_schema() {
    sqlite3 -cmd ".timeout 5000" "$1" \
        "ALTER TABLE entries ADD COLUMN content_hash TEXT;" >/dev/null 2>&1
    sqlite3 -cmd ".timeout 5000" "$1" \
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_entries_dedupe ON entries(session_id, entry_type, content_hash) WHERE content_hash IS NOT NULL;" >/dev/null 2>&1
}

# Session-binding marker (atomic tmp+mv): the companion MCP server — a
# separate long-lived process — binds its active session id from this
# run-dir file. Without it, a stale marker from an earlier session causes
# cross-session misattribution of journal/budget writes. Mirrors
# pre_send.py:_write_session_marker; must run BEFORE any early exit.
if [ -n "$SESSION_ID" ]; then
    RUN_DIR="${TOKENPAK_COMPANION_JOURNAL_DIR:-$HOME/.tokenpak/companion}/run"
    _TP_CUR=""
    if [ -f "$RUN_DIR/current-session" ]; then
        IFS= read -r _TP_CUR < "$RUN_DIR/current-session" 2>/dev/null
    fi
    # Hot-path guard: rewrite only on session change (builtin read, no spawns).
    if [ "$_TP_CUR" != "$SESSION_ID" ]; then
        mkdir -p "$RUN_DIR" 2>/dev/null
        if printf '%s' "$SESSION_ID" > "$RUN_DIR/current-session.$$.tmp" 2>/dev/null; then
            mv -f "$RUN_DIR/current-session.$$.tmp" "$RUN_DIR/current-session" 2>/dev/null \
                || rm -f "$RUN_DIR/current-session.$$.tmp" 2>/dev/null
        fi
    fi
fi

# Token estimation from file size (instant via stat)
TOKENS=0
if [ -n "$TRANSCRIPT" ] && [ -f "$TRANSCRIPT" ]; then
    FILE_SIZE=$(stat -c%s "$TRANSCRIPT" 2>/dev/null || stat -f%z "$TRANSCRIPT" 2>/dev/null || echo 0)
    TOKENS=$((FILE_SIZE / 4))
fi

[ "$TOKENS" -eq 0 ] && exit 0

# Format token count with thousands separators (pure bash)
TOKENS_FMT="$TOKENS"
if [ "$TOKENS" -ge 1000 ]; then
    _TP_N="$TOKENS"
    TOKENS_FMT=""
    while [ "${#_TP_N}" -gt 3 ]; do
        _TP_PART="${_TP_N: -3}"
        _TP_N="${_TP_N:0:${#_TP_N}-3}"
        if [ -n "$TOKENS_FMT" ]; then
            TOKENS_FMT="${_TP_PART},${TOKENS_FMT}"
        else
            TOKENS_FMT="$_TP_PART"
        fi
    done
    TOKENS_FMT="${_TP_N},${TOKENS_FMT}"
fi

# Rate lookup: shared TSV snapshot generated by the companion Codex launcher.
# Fallback rate 3 matches the registry's unknown/default input rate.
RATES_FILE="${TOKENPAK_COMPANION_RATES_FILE:-$HOME/.tokenpak/companion/run/model_rates.tsv}"
RATE=3
if [ -n "$MODEL" ] && [ -f "$RATES_FILE" ]; then
    RATE=$(awk -F'\t' -v m="$MODEL" '$1 == m { print $2; exit }' "$RATES_FILE" 2>/dev/null)
    if [ -z "$RATE" ]; then
        RATE=$(awk -F'\t' -v m="$MODEL" '
            BEGIN { best_len = 0; best = "" }
            index(m, $1) == 1 && length($1) > best_len { best_len = length($1); best = $2 }
            END { if (best != "") print best }
        ' "$RATES_FILE" 2>/dev/null)
    fi
    case "$RATE" in
        ''|*[!0-9]*) RATE=3 ;;
    esac
fi

# Integer math in microdollars: USD/Mtoken => tokens * rate microdollars.
COST_MICRO=$((TOKENS * RATE))
COST_DOLLARS="$(( COST_MICRO / 1000000 )).$(printf '%06d' $(( COST_MICRO % 1000000 )) )"

# Budget check (only if TOKENPAK_COMPANION_BUDGET is set and > 0)
BUDGET="${TOKENPAK_COMPANION_BUDGET:-0}"
BUDGET_TAG=""

if [ "$BUDGET" != "0" ] && [ -n "$BUDGET" ]; then
    JOURNAL_DIR="${TOKENPAK_COMPANION_JOURNAL_DIR:-$HOME/.tokenpak/companion}"
    BUDGET_DB="$JOURNAL_DIR/budget.db"
    TODAY=$(date +%Y-%m-%d)
    DAILY_TOTAL="0.0"

    if ! command -v sqlite3 >/dev/null 2>&1; then
        _tp_block_budget "tokenpak: budget check unavailable (sqlite3 missing) with TOKENPAK_COMPANION_BUDGET set"
    fi

    # Truthful daily spend: per (session, day) sum the actual rows when any
    # exist (rows with a model are actuals), otherwise take the largest
    # estimate — counts each message once instead of summing the cumulative
    # pre-send estimate series plus actuals. Mirrors the python readers
    # (companion/_sqlite.py DAILY_SPEND_SQL) without referencing the 'kind'
    # column so it also works on not-yet-migrated databases.
    if [ -f "$BUDGET_DB" ]; then
        DAILY_TOTAL=$(sqlite3 -cmd ".timeout 5000" "$BUDGET_DB" \
            "SELECT COALESCE(SUM(session_spend), 0) FROM (
                 SELECT CASE
                     WHEN SUM(CASE WHEN model != '' THEN 1 ELSE 0 END) > 0
                     THEN SUM(CASE WHEN model != '' THEN estimated_cost ELSE 0 END)
                     ELSE MAX(estimated_cost)
                 END AS session_spend
                 FROM companion_costs WHERE date = '$TODAY' GROUP BY session_id
             );" 2>/dev/null || echo "0.0")
        [ -z "$DAILY_TOTAL" ] && DAILY_TOTAL="0.0"
    fi

    # Compare using integer microdollars
    BUDGET_MICRO=$(_tp_to_micro "$BUDGET" || echo "")
    DAILY_MICRO=$(_tp_to_micro "$DAILY_TOTAL" || echo "")
    EST_MICRO=$((TOKENS * RATE))

    if [ -z "$BUDGET_MICRO" ] || [ -z "$DAILY_MICRO" ]; then
        _tp_block_budget "tokenpak: budget check unavailable (invalid budget accounting value)"
    fi

    if [ "$((DAILY_MICRO + EST_MICRO))" -gt "$BUDGET_MICRO" ] 2>/dev/null; then
        _tp_block_budget "tokenpak: budget exceeded (\$$DAILY_TOTAL / \$$BUDGET daily)"
    fi

    # Budget percentage tag
    if [ "${BUDGET_MICRO:-0}" -gt 0 ] 2>/dev/null; then
        PCT=$((DAILY_MICRO * 100 / BUDGET_MICRO))
        [ "$PCT" -gt 50 ] && BUDGET_TAG="  budget ${PCT}%"
    fi
fi

# Print cost estimate to stderr (visible in TUI)
if [ "${TOKENPAK_COMPANION_SHOW_COST:-1}" != "0" ]; then
    MODEL_TAG=""
    [ -n "$MODEL" ] && MODEL_TAG=" ($MODEL)"
    printf 'tokenpak: ~%s tokens  est $%s%s%s\n' "$TOKENS_FMT" "$COST_DOLLARS" "$MODEL_TAG" "$BUDGET_TAG" >&2
fi

if [ -n "$SESSION_ID" ]; then
    JOURNAL_DIR="${TOKENPAK_COMPANION_JOURNAL_DIR:-$HOME/.tokenpak/companion}"
    JOURNAL_DB="$JOURNAL_DIR/journal.db"
    if [ -f "$JOURNAL_DB" ] && command -v sqlite3 >/dev/null 2>&1; then
        TIMESTAMP=$(date +%s)
        ENTRY_CONTENT="prompt submitted (~${TOKENS_FMT} tokens, est \$$COST_DOLLARS, model: ${MODEL:-unknown})"
        ENTRY_HASH=$(_tp_entry_hash 'auto' "$ENTRY_CONTENT" '{}')
        {
            _tp_ensure_dedupe_schema "$JOURNAL_DB"
            sqlite3 -cmd ".timeout 5000" "$JOURNAL_DB" \
                "INSERT OR IGNORE INTO entries (session_id, timestamp, entry_type, content, metadata_json, content_hash)
                 VALUES ('$SESSION_ID', $TIMESTAMP, 'auto', '$ENTRY_CONTENT', '{}', NULLIF('$ENTRY_HASH', ''));" 2>/dev/null
        } &
    fi
fi

exit 0
